[package]
name = "os_project"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
libc = "0.2.164"
procfs = "0.14"
users = "0.11"
sysinfo = "0.21"
termion = "4.0.3"
crossterm = "0.28.1"
